check program rclone_cloud_backup with path "/etc/monit/scripts/rclone_cloud_backup.sh"
with timeout 60 seconds
    if status > 0 then alert
    alert my_gmail with mail-format  {
        subject: Google Drive backup state changed
    }
