check program service_status with path "/etc/monit/scripts/service_status_collect.sh"
with timeout 60 seconds
every 2 cycles
    if status > 0
        for 2 times within 3 cycles then alert
    alert my_gmail with mail-format  {     # use local format
        subject: 🧭 Service status collector failed
    }
    with reminder on 2880 cycles
