#!/bin/bash
file="/var/log/apcupsd.log"

echo "😪 Father, I failed you.. Turning off all PCs in network " >> $file
monit # force read this file

# send command to main pc, routers etc

login="<WINDOWS_SHUTDOWN_USER>"
password="<WINDOWS_SHUTDOWN_PASSWORD>"
win_ip="<WINDOWS_HOST_IP>"
net rpc shutdown -f -t 0 -C 'APCUPSD' -U $login%$password -I $win_ip

login="<SSH_SHUTDOWN_USER>"
host="<SSH_SHUTDOWN_HOST>"
ssh -t "$login@$host" 'shutdown -r 0'
